/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Calculator;

/**
 *
 * @author htk11
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator2
     */
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton_Precent = new javax.swing.JButton();
        jButton_Clean_E = new javax.swing.JButton();
        jButton_Clean = new javax.swing.JButton();
        jButton_BackSpace = new javax.swing.JButton();
        jButton_1_Divine_X = new javax.swing.JButton();
        jButton_Square = new javax.swing.JButton();
        jButton_Sqrt = new javax.swing.JButton();
        jButton_Divine = new javax.swing.JButton();
        jButton_Number7 = new javax.swing.JButton();
        jButton_Number8 = new javax.swing.JButton();
        jButton_Number9 = new javax.swing.JButton();
        jButton_Multi = new javax.swing.JButton();
        jButton_Number4 = new javax.swing.JButton();
        jButton_Number5 = new javax.swing.JButton();
        jButton_Number6 = new javax.swing.JButton();
        jButton_Minus = new javax.swing.JButton();
        jButton_Number1 = new javax.swing.JButton();
        jButton_Number2 = new javax.swing.JButton();
        jButton_Number3 = new javax.swing.JButton();
        jButton_Plus = new javax.swing.JButton();
        jButton2_Plus_Or_Minus = new javax.swing.JButton();
        jButton_Number0 = new javax.swing.JButton();
        jButton_Comma = new javax.swing.JButton();
        jButton_Is_Equal_To = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        javax.swing.JTextField jTextField_Result = new javax.swing.JTextField();
        jTextField_Display = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        setPreferredSize(new java.awt.Dimension(500, 560));

        jPanel2.setLayout(new java.awt.GridLayout(6, 4));

        jButton_Precent.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_Precent.setText("%");
        jPanel2.add(jButton_Precent);

        jButton_Clean_E.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_Clean_E.setText("CE");
        jPanel2.add(jButton_Clean_E);

        jButton_Clean.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_Clean.setText("C");
        jPanel2.add(jButton_Clean);

        jButton_BackSpace.setText("⌫ ");
        jPanel2.add(jButton_BackSpace);

        jButton_1_Divine_X.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_1_Divine_X.setText("1/X");
        jPanel2.add(jButton_1_Divine_X);

        jButton_Square.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_Square.setText("X^2");
        jPanel2.add(jButton_Square);

        jButton_Sqrt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_Sqrt.setText("sqrt(X)");
        jPanel2.add(jButton_Sqrt);

        jButton_Divine.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_Divine.setText("/");
        jPanel2.add(jButton_Divine);

        jButton_Number7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_Number7.setText("7");
        jPanel2.add(jButton_Number7);

        jButton_Number8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_Number8.setText("8");
        jPanel2.add(jButton_Number8);

        jButton_Number9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_Number9.setText("9");
        jPanel2.add(jButton_Number9);

        jButton_Multi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_Multi.setText("*");
        jPanel2.add(jButton_Multi);

        jButton_Number4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_Number4.setText("4");
        jPanel2.add(jButton_Number4);

        jButton_Number5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_Number5.setText("5");
        jPanel2.add(jButton_Number5);

        jButton_Number6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_Number6.setText("6");
        jPanel2.add(jButton_Number6);

        jButton_Minus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_Minus.setText("-");
        jPanel2.add(jButton_Minus);

        jButton_Number1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_Number1.setText("1");
        jPanel2.add(jButton_Number1);

        jButton_Number2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_Number2.setText("2");
        jPanel2.add(jButton_Number2);

        jButton_Number3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_Number3.setText("3");
        jPanel2.add(jButton_Number3);

        jButton_Plus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_Plus.setText("+");
        jPanel2.add(jButton_Plus);

        jButton2_Plus_Or_Minus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2_Plus_Or_Minus.setText("+/-");
        jButton2_Plus_Or_Minus.setToolTipText("");
        jButton2_Plus_Or_Minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_Plus_Or_MinusActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2_Plus_Or_Minus);

        jButton_Number0.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_Number0.setText("0");
        jPanel2.add(jButton_Number0);

        jButton_Comma.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_Comma.setText(",");
        jPanel2.add(jButton_Comma);

        jButton_Is_Equal_To.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton_Is_Equal_To.setText("=");
        jPanel2.add(jButton_Is_Equal_To);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new java.awt.GridLayout(2, 1));

        jTextField_Result.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField_Result.setPreferredSize(new java.awt.Dimension(62, 30));
        jPanel1.add(jTextField_Result);

        jTextField_Display.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(jTextField_Display);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2_Plus_Or_MinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_Plus_Or_MinusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2_Plus_Or_MinusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2_Plus_Or_Minus;
    private javax.swing.JButton jButton_1_Divine_X;
    private javax.swing.JButton jButton_BackSpace;
    private javax.swing.JButton jButton_Clean;
    private javax.swing.JButton jButton_Clean_E;
    private javax.swing.JButton jButton_Comma;
    private javax.swing.JButton jButton_Divine;
    private javax.swing.JButton jButton_Is_Equal_To;
    private javax.swing.JButton jButton_Minus;
    private javax.swing.JButton jButton_Multi;
    private javax.swing.JButton jButton_Number0;
    private javax.swing.JButton jButton_Number1;
    private javax.swing.JButton jButton_Number2;
    private javax.swing.JButton jButton_Number3;
    private javax.swing.JButton jButton_Number4;
    private javax.swing.JButton jButton_Number5;
    private javax.swing.JButton jButton_Number6;
    private javax.swing.JButton jButton_Number7;
    private javax.swing.JButton jButton_Number8;
    private javax.swing.JButton jButton_Number9;
    private javax.swing.JButton jButton_Plus;
    private javax.swing.JButton jButton_Precent;
    private javax.swing.JButton jButton_Sqrt;
    private javax.swing.JButton jButton_Square;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField_Display;
    // End of variables declaration//GEN-END:variables
}
